server:
  port: 7089
spring:
  datasource:
    password: 'root-India123'
    url: jdbc:mysql://localhost:3306/employee?useTimezone=true&serverTimezone=GMT
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: mysql
